spring.application.name=dev
server.port=8080

# Cấu hình PostgreSQL (NeonDB)
spring.datasource.url=jdbc:postgresql://ep-weathered-credit-az91bmza-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CNjSauYQeH12
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate / JPA
# Ép Hibernate drop hết bảng cũ và tạo lại toàn bộ khi ứng dụng khởi chạy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# TTL cho token login
token.ttl=360000000000